import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  serverExternalPackages: ['sharp'],
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'media.mehrnews.com' },
      { protocol: 'https', hostname: 'img9.irna.ir' },
      { protocol: 'https', hostname: 'www.irna.ir' },
      { protocol: 'https', hostname: 'www.mehrnews.com' },
      { protocol: 'https', hostname: 'media.isna.ir' },
      { protocol: 'https', hostname: 'www.isna.ir' },
      { protocol: 'https', hostname: 'media.farsnews.ir' },
      { protocol: 'https', hostname: 'www.farsnews.ir' },
      { protocol: 'https', hostname: 'media.tasnimnews.com' },
      { protocol: 'https', hostname: 'www.tasnimnews.com' },
      { protocol: 'https', hostname: 'bashgah.net' },
      { protocol: 'https', hostname: 'asrebooshehr.ir' },
      { protocol: 'https', hostname: 'booshehr.ir' },
      { protocol: 'https', hostname: 'boresseir.com' },
      { protocol: 'https', hostname: 'www.boresseir.com' },
      { protocol: 'https', hostname: 'booshahr24.ir' },
      { protocol: 'https', hostname: 'youngpress.ir' },
      { protocol: 'https', hostname: '*.public.blob.vercel-storage.com' },
      { protocol: 'https', hostname: 'kayhan.ir' },
      { protocol: 'https', hostname: 'cdn.sharghdaily.com' },
      { protocol: 'https', hostname: 'www.sharghdaily.com' },
      { protocol: 'https', hostname: 'media.irannewspaper.ir' },
      { protocol: 'https', hostname: 'cdn-newspaper.inn.ir' },
      { protocol: 'https', hostname: 'media.ettelaat.com' },
      { protocol: 'https', hostname: 'jamejamdaily.ir' },
      { protocol: 'https', hostname: 'javanonline.ir' },
      { protocol: 'https', hostname: 'vatanemrooz.ir' },
      { protocol: 'https', hostname: 'etemadnewspaper.ir' },
      { protocol: 'https', hostname: 'www.etemadnewspaper.ir' },
      { protocol: 'https', hostname: 'cdn.donya-e-eqtesad.com' },
      { protocol: 'https', hostname: 'goaldaily.ir' },
      { protocol: 'https', hostname: 'bamdadjonub.ir' },
      { protocol: 'https', hostname: '*.telegram.org' },
      { protocol: 'https', hostname: 'tasnimnews.ir' },
      { protocol: 'https', hostname: '*.tasnimnews.ir' },
      { protocol: 'https', hostname: 'www.pishkhan.com' },
      { protocol: 'https', hostname: 'khorasanonline.ir' },
      { protocol: 'https', hostname: '*.khorasanonline.ir' },
    ],
  },
};

export default nextConfig;
