export type OccasionType = 'happy' | 'mourning' | 'official' | 'normal';

export interface OccasionColors {
  headerBg: string;
  headerGradient: string;
  navBg: string;
  tickerBg: string;
  footerBg: string;
  accent: string;
  textPrimary: string;
  textSecondary: string;
}

export interface Occasion {
  id: string;
  name: string;
  type: OccasionType;
  hijriMonths?: number[];
  hijriDays?: number[];
  jalaliMonths?: number[];
  jalaliDays?: number[];
  startDay?: number;
  endDay?: number;
  message: string;
  subMessage?: string;
  colors: OccasionColors;
  bannerImage?: string;
  showFloral?: boolean;
  showCandle?: boolean;
  showFlag?: boolean;
  priority: number;
}

const happyColors: OccasionColors = {
  headerBg: '#0f2440',
  headerGradient: 'from-emerald-900 via-green-800 to-emerald-900',
  navBg: 'from-[#1a5c2a] via-[#22703a] to-[#1a5c2a]',
  tickerBg: 'from-[#0d3318] via-[#145228] to-[#0d3318]',
  footerBg: '#0f2440',
  accent: '#C9A96E',
  textPrimary: '#ffffff',
  textSecondary: '#C9A96E',
};

const mourningColors: OccasionColors = {
  headerBg: '#1a1a1a',
  headerGradient: 'from-gray-900 via-black to-gray-900',
  navBg: 'from-[#1a1a1a] via-[#2a2a2a] to-[#1a1a1a]',
  tickerBg: 'from-[#111111] via-[#1a1a1a] to-[#111111]',
  footerBg: '#111111',
  accent: '#888888',
  textPrimary: '#ffffff',
  textSecondary: '#aaaaaa',
};

const officialColors: OccasionColors = {
  headerBg: '#0f2440',
  headerGradient: 'from-[#1B365D] via-[#1e3a64] to-[#1B365D]',
  navBg: 'from-[#1B365D] via-[#1e3a64] to-[#1B365D]',
  tickerBg: 'from-[#0a1628] via-[#0f1d35] to-[#0a1628]',
  footerBg: '#0f2440',
  accent: '#C9A96E',
  textPrimary: '#ffffff',
  textSecondary: '#C9A96E',
};

export const occasions: Occasion[] = [
  {
    id: 'nowruz',
    name: 'نوروز',
    type: 'happy',
    jalaliMonths: [1],
    jalaliDays: [1, 2, 3, 4],
    message: 'سال نو مبارک',
    subMessage: 'نوروزتان پیروز، سالتان پر از موفقیت',
    colors: {
      ...happyColors,
      headerGradient: 'from-emerald-800 via-green-700 to-emerald-800',
      navBg: 'from-[#15803d] via-[#22c55e] to-[#15803d]',
    },
    showFloral: true,
    priority: 100,
  },
  {
    id: 'sizdah-bedar',
    name: 'سیزده بدر',
    type: 'happy',
    jalaliMonths: [1],
    jalaliDays: [13],
    message: 'سیزده بدر مبارک',
    subMessage: 'روز طبیعت، روز شادی و خوشبختی',
    colors: happyColors,
    showFloral: true,
    priority: 90,
  },
  {
    id: 'tasua-ashura',
    name: 'تاسوعای حسینی',
    type: 'mourning',
    hijriMonths: [1],
    hijriDays: [9],
    message: 'تاسوعای حسینی تسلیت باد',
    subMessage: 'ایام سوگواری سیدالشهدا (ع)',
    colors: mourningColors,
    showCandle: true,
    priority: 95,
  },
  {
    id: 'ashura',
    name: 'عاشورای حسینی',
    type: 'mourning',
    hijriMonths: [1],
    hijriDays: [10],
    message: 'عاشورای حسینی تسلیت باد',
    subMessage: 'روز عزای سالار شهیدان (ع)',
    colors: mourningColors,
    showCandle: true,
    priority: 100,
  },
  {
    id: 'arbaeen',
    name: 'اربعین حسینی',
    type: 'mourning',
    hijriMonths: [2],
    hijriDays: [20],
    message: 'اربعین حسینی تسلیت باد',
    subMessage: 'چهلمین روز شهادت امام حسین (ع)',
    colors: mourningColors,
    showCandle: true,
    priority: 95,
  },
  {
    id: 'mehraj',
    name: 'مبعث پیامبر (ص)',
    type: 'happy',
    hijriMonths: [3],
    hijriDays: [27],
    message: 'بعثت پیامبر (ص) مبارک',
    subMessage: 'جشن بعثت خاتم المرسلین',
    colors: {
      ...happyColors,
      headerGradient: 'from-yellow-800 via-amber-700 to-yellow-800',
      navBg: 'from-[#b45309] via-[#d97706] to-[#b45309]',
    },
    showFloral: true,
    priority: 90,
  },
  {
    id: 'shab-e-miraj',
    name: 'شب معراج',
    type: 'happy',
    hijriMonths: [7],
    hijriDays: [27],
    message: 'شب معراج مبارک',
    subMessage: 'سالروز معراج پیامبر (ص)',
    colors: {
      ...happyColors,
      headerGradient: 'from-indigo-900 via-blue-800 to-indigo-900',
      navBg: 'from-[#312e81] via-[#4338ca] to-[#312e81]',
    },
    priority: 70,
  },
  {
    id: 'shab-e-barat',
    name: 'شب نیمه شعبان',
    type: 'happy',
    hijriMonths: [8],
    hijriDays: [15],
    message: 'نیمه شعبان مبارک',
    subMessage: 'میلاد منجی عالم بشریت',
    colors: {
      ...happyColors,
      headerGradient: 'from-sky-800 via-blue-700 to-sky-800',
      navBg: 'from-[#0369a1] via-[#0ea5e9] to-[#0369a1]',
    },
    showFloral: true,
    priority: 85,
  },
  {
    id: 'ramadan-start',
    name: 'آغاز ماه رمضان',
    type: 'happy',
    hijriMonths: [9],
    hijriDays: [1],
    message: 'ماه رمضان مبارک',
    subMessage: 'ماه رحمت و مغفرت فرا رسید',
    colors: {
      ...happyColors,
      headerGradient: 'from-violet-900 via-purple-800 to-violet-900',
      navBg: 'from-[#581c87] via-[#7c3aed] to-[#581c87]',
    },
    showFloral: true,
    priority: 90,
  },
  {
    id: 'qadr-nights',
    name: 'شبهای قدر',
    type: 'mourning',
    hijriMonths: [9],
    hijriDays: [21, 23, 25, 27],
    message: 'شبهای قدر',
    subMessage: 'شب قدر از هزار ماه بهتر است',
    colors: {
      ...mourningColors,
      headerGradient: 'from-indigo-950 via-purple-950 to-indigo-950',
    },
    showCandle: true,
    priority: 95,
  },
  {
    id: 'eid-fitr',
    name: 'عید فطر',
    type: 'happy',
    hijriMonths: [10],
    hijriDays: [1],
    message: 'عید فطر مبارک',
    subMessage: 'عید سعید فطر، جشن بندگی خدا',
    colors: {
      ...happyColors,
      headerGradient: 'from-emerald-800 via-green-600 to-emerald-800',
      navBg: 'from-[#059669] via-[#34d399] to-[#059669]',
    },
    showFloral: true,
    priority: 100,
  },
  {
    id: 'eid-qorban',
    name: 'عید قربان',
    type: 'happy',
    hijriMonths: [12],
    hijriDays: [10],
    message: 'عید قربان مبارک',
    subMessage: 'جشن بندگی و ایثار',
    colors: {
      ...happyColors,
      headerGradient: 'from-amber-800 via-yellow-600 to-amber-800',
      navBg: 'from-[#b45309] via-[#eab308] to-[#b45309]',
    },
    showFloral: true,
    priority: 90,
  },
  {
    id: 'mabani',
    name: 'روز مباهله',
    type: 'happy',
    hijriMonths: [6],
    hijriDays: [24],
    message: 'روز مباهله مبارک',
    subMessage: '',
    colors: happyColors,
    priority: 50,
  },
  {
    id: 'velayat',
    name: ' ولاyat علی (ع)',
    type: 'happy',
    hijriMonths: [3],
    hijriDays: [13],
    message: 'میلاد امام علی (ع) مبارک',
    subMessage: 'روز پدر',
    colors: {
      ...happyColors,
      headerGradient: 'from-green-800 via-emerald-600 to-green-800',
      navBg: 'from-[#166534] via-[#4ade80] to-[#166534]',
    },
    showFloral: true,
    priority: 85,
  },
  {
    id: 'shahrivar-22',
    name: 'پیروزی انقلاب اسلامی',
    type: 'official',
    jalaliMonths: [11],
    jalaliDays: [22],
    message: 'دهه فجر مبارک',
    subMessage: 'پیروزی انقلاب اسلامی ایران',
    colors: {
      ...officialColors,
      headerGradient: 'from-[#1B365D] via-[#2a5080] to-[#1B365D]',
      navBg: 'from-[#1B365D] via-[#2a5080] to-[#1B365D]',
    },
    showFlag: true,
    priority: 90,
  },
  {
    id: 'dey-13',
    name: 'قیام ۱۵ خرداد',
    type: 'official',
    jalaliMonths: [3],
    jalaliDays: [15],
    message: 'سالروز قیام خونین ۱۵ خرداد',
    subMessage: '',
    colors: officialColors,
    showFlag: true,
    priority: 70,
  },
  {
    id: 'shohada',
    name: 'روز شهدا',
    type: 'mourning',
    jalaliMonths: [12],
    jalaliDays: [22],
    message: 'گرامیداشت یاد و خاطره شهدا',
    subMessage: 'روز بزرگداشت شهدا',
    colors: mourningColors,
    showCandle: true,
    priority: 80,
  },
  {
    id: 'rahbar',
    name: 'سالروز رحلت امام خمینی (ره)',
    type: 'mourning',
    hijriMonths: [3],
    hijriDays: [14],
    message: 'سالروز رحلت امام خمینی (ره)',
    subMessage: 'بنیان‌گذار جمهوری اسلامی ایران',
    colors: mourningColors,
    showCandle: true,
    priority: 85,
  },
  {
    id: 'qods-day',
    name: 'روز قدس',
    type: 'official',
    jalaliMonths: [2],
    jalaliDays: [27],
    message: 'روز قدس مبارک',
    subMessage: 'روز حمایت از مردم مظلوم فلسطین',
    colors: {
      ...officialColors,
      navBg: 'from-[#1B365D] via-[#2a5080] to-[#1B365D]',
    },
    showFlag: true,
    priority: 80,
  },
  {
    id: 'hefta-defa',
    name: 'هفته دفاع مقدس',
    type: 'official',
    jalaliMonths: [7],
    jalaliDays: [1, 2, 3, 4, 5, 6, 7],
    message: 'هفته دفاع مقدس گرامی باد',
    subMessage: 'یاد و خاطره رزمندگان اسلام',
    colors: {
      ...officialColors,
      navBg: 'from-[#1B365D] via-[#0f2d50] to-[#1B365D]',
    },
    showFlag: true,
    priority: 75,
  },
  {
    id: 'hefta-sonnat',
    name: 'هفته وحدت',
    type: 'official',
    hijriMonths: [3],
    hijriDays: [12, 13, 14, 15, 16, 17],
    message: 'هفته وحدت مبارک',
    subMessage: 'وحدت حوزه و دانشگاه',
    colors: officialColors,
    priority: 60,
  },
  {
    id: 'shahed-29',
    name: 'شهادت رئیسعلی دلواری',
    type: 'mourning',
    jalaliMonths: [6],
    jalaliDays: [12],
    message: 'یاد و خاطره شهید رئیسعلی دلواری گرامی باد',
    subMessage: 'قهرمان مقاومت بوشهر',
    colors: mourningColors,
    showCandle: true,
    priority: 65,
  },
  {
    id: 'shahed-solimani',
    name: 'شهادت سردار سلیمانی',
    type: 'mourning',
    jalaliMonths: [10],
    jalaliDays: [13],
    message: 'شهادت سردار سپهبد قاسم سلیمانی تسلیت باد',
    subMessage: 'مرد میدان',
    colors: mourningColors,
    showCandle: true,
    priority: 85,
  },
  {
    id: 'padafand',
    name: 'روز نیروی دریایی',
    type: 'official',
    jalaliMonths: [8],
    jalaliDays: [7],
    message: 'روز نیروی دریایی گرامی باد',
    subMessage: 'دفاع از آب‌های سرزمینی',
    colors: {
      ...officialColors,
      navBg: 'from-[#0c4a6e] via-[#0369a1] to-[#0c4a6e]',
    },
    showFlag: true,
    priority: 60,
  },
  {
    id: 'mowlid-nabawi',
    name: 'میلاد پیامبر (ص)',
    type: 'happy',
    hijriMonths: [3],
    hijriDays: [12],
    message: 'میلاد نبی مکرم اسلام مبارک',
    subMessage: 'سالروز تولد حضرت محمد (ص) پیامبر رحمت',
    colors: {
      ...happyColors,
      headerGradient: 'from-amber-800 via-yellow-600 to-amber-800',
      navBg: 'from-[#92400e] via-[#f59e0b] to-[#92400e]',
    },
    showFloral: true,
    priority: 95,
  },
  {
    id: 'wafat-nabawi',
    name: 'رحلت پیامبر (ص)',
    type: 'mourning',
    hijriMonths: [2],
    hijriDays: [28],
    message: 'سالروز رحلت پیامبر (ص) تسلیت باد',
    subMessage: 'آخرین پیامبر خدا، خاتم المرسلین',
    colors: mourningColors,
    showCandle: true,
    priority: 95,
  },
  {
    id: 'shahadat-hassan',
    name: 'شهادت امام حسن مجتبی (ع)',
    type: 'mourning',
    hijriMonths: [2],
    hijriDays: [28],
    message: 'شهادت امام حسن مجتبی (ع) تسلیت باد',
    subMessage: 'امام دوم شیعیان',
    colors: mourningColors,
    showCandle: true,
    priority: 85,
  },
  {
    id: 'mowlid-hassan',
    name: 'میلاد امام حسن مجتبی (ع)',
    type: 'happy',
    hijriMonths: [3],
    hijriDays: [15],
    message: 'میلاد امام حسن مجتبی (ع) مبارک',
    subMessage: 'امام دوم شیعیان',
    colors: {
      ...happyColors,
      headerGradient: 'from-teal-800 via-cyan-600 to-teal-800',
      navBg: 'from-[#115e59] via-[#06b6d4] to-[#115e59]',
    },
    showFloral: true,
    priority: 80,
  },
  {
    id: 'shahadat-hossein',
    name: 'شهادت امام حسین (ع)',
    type: 'mourning',
    hijriMonths: [1],
    hijriDays: [10],
    message: 'شهادت امام حسین (ع) تسلیت باد',
    subMessage: 'سیدالشهدا، امام سوم شیعیان',
    colors: mourningColors,
    showCandle: true,
    priority: 100,
  },
  {
    id: 'mowlid-hossein',
    name: 'میلاد امام حسین (ع)',
    type: 'happy',
    hijriMonths: [8],
    hijriDays: [3],
    message: 'میلاد امام حسین (ع) مبارک',
    subMessage: 'سومین امام شیعیان',
    colors: {
      ...happyColors,
      headerGradient: 'from-emerald-800 via-green-600 to-emerald-800',
      navBg: 'from-[#065f46] via-[#10b981] to-[#065f46]',
    },
    showFloral: true,
    priority: 80,
  },
  {
    id: 'shahadat-ali',
    name: 'شهادت امام علی (ع)',
    type: 'mourning',
    hijriMonths: [9],
    hijriDays: [21],
    message: 'شهادت امام علی (ع) تسلیت باد',
    subMessage: 'اولین امام شیعیان، مولی الموحدین',
    colors: mourningColors,
    showCandle: true,
    priority: 95,
  },
  {
    id: 'mowlid-ali',
    name: 'میلاد امام علی (ع)',
    type: 'happy',
    hijriMonths: [3],
    hijriDays: [13],
    message: 'میلاد امام علی (ع) و روز پدر مبارک',
    subMessage: 'اولین امام شیعیان',
    colors: {
      ...happyColors,
      headerGradient: 'from-green-800 via-emerald-600 to-green-800',
      navBg: 'from-[#166534] via-[#4ade80] to-[#166534]',
    },
    showFloral: true,
    priority: 90,
  },
  {
    id: 'shahadat-musa-kazim',
    name: 'شهادت امام موسی کاظم (ع)',
    type: 'mourning',
    hijriMonths: [1],
    hijriDays: [25],
    message: 'شهادت امام موسی کاظم (ع) تسلیت باد',
    subMessage: 'هفتمین امام شیعیان',
    colors: mourningColors,
    showCandle: true,
    priority: 75,
  },
  {
    id: 'mowlid-reza',
    name: 'میلاد امام رضا (ع)',
    type: 'happy',
    hijriMonths: [11],
    hijriDays: [11],
    message: 'میلاد امام رضا (ع) مبارک',
    subMessage: 'هشتمین امام شیعیان',
    colors: {
      ...happyColors,
      headerGradient: 'from-blue-800 via-indigo-600 to-blue-800',
      navBg: 'from-[#1e3a8a] via-[#6366f1] to-[#1e3a8a]',
    },
    showFloral: true,
    priority: 85,
  },
  {
    id: 'shahadat-reza',
    name: 'شهادت امام رضا (ع)',
    type: 'mourning',
    hijriMonths: [2],
    hijriDays: [30],
    message: 'شهادت امام رضا (ع) تسلیت باد',
    subMessage: 'هشتمین امام شیعیان',
    colors: mourningColors,
    showCandle: true,
    priority: 80,
  },
  {
    id: 'mowlid-javad',
    name: 'میلاد امام جواد (ع)',
    type: 'happy',
    hijriMonths: [10],
    hijriDays: [10],
    message: 'میلاد امام جواد (ع) مبارک',
    subMessage: 'نهمین امام شیعیان',
    colors: {
      ...happyColors,
      headerGradient: 'from-purple-800 via-violet-600 to-purple-800',
      navBg: 'from-[#6b21a8] via-[#a78bfa] to-[#6b21a8]',
    },
    showFloral: true,
    priority: 75,
  },
  {
    id: 'shahadat-hadi',
    name: 'شهادت امام هادی (ع)',
    type: 'mourning',
    hijriMonths: [3],
    hijriDays: [3],
    message: 'شهادت امام هادی (ع) تسلیت باد',
    subMessage: 'دهمین امام شیعیان',
    colors: mourningColors,
    showCandle: true,
    priority: 75,
  },
  {
    id: 'shahadat-hassan-asgari',
    name: 'شهادت امام حسن عسکری (ع)',
    type: 'mourning',
    hijriMonths: [3],
    hijriDays: [8],
    message: 'شهادت امام حسن عسکری (ع) تسلیت باد',
    subMessage: 'یازدهمین امام شیعیان',
    colors: mourningColors,
    showCandle: true,
    priority: 75,
  },
  {
    id: 'mowlid-mahdi',
    name: 'میلاد امام زمان (عج)',
    type: 'happy',
    hijriMonths: [8],
    hijriDays: [15],
    message: 'نیمه شعبان، میلاد امام زمان (عج) مبارک',
    subMessage: 'ولی عصر، امام دوازدهم شیعیان',
    colors: {
      ...happyColors,
      headerGradient: 'from-sky-800 via-cyan-500 to-sky-800',
      navBg: 'from-[#075985] via-[#22d3ee] to-[#075985]',
    },
    showFloral: true,
    priority: 100,
  },
];

export function getActiveOccasion(
  jalaliDay: number,
  jalaliMonth: number,
  hijriDay: number,
  hijriMonth: number
): Occasion | null {
  const candidates = occasions.filter((o) => {
    if (o.jalaliMonths && o.jalaliDays) {
      if (o.jalaliMonths.includes(jalaliMonth) && o.jalaliDays.includes(jalaliDay)) return true;
    }
    if (o.hijriMonths && o.hijriDays) {
      if (o.hijriMonths.includes(hijriMonth) && o.hijriDays.includes(hijriDay)) return true;
    }
    return false;
  });

  if (candidates.length === 0) return null;

  candidates.sort((a, b) => b.priority - a.priority);
  return candidates[0];
}

export const defaultColors: OccasionColors = {
  headerBg: '#0f2440',
  headerGradient: 'from-[#1B365D] via-[#1e3a64] to-[#1B365D]',
  navBg: 'from-[#1B365D] via-[#1e3a64] to-[#1B365D]',
  tickerBg: 'from-[#0a1628] via-[#0f1d35] to-[#0a1628]',
  footerBg: '#0f2440',
  accent: '#C9A96E',
  textPrimary: '#ffffff',
  textSecondary: '#C9A96E',
};
